services:
  authdb-prod:
    container_name: authdb-prod
    image: postgres:17
    environment:
      - POSTGRES_USER=tacauthuser
      - POSTGRES_PASSWORD=tacauthpass
      - POSTGRES_DB=tacauthdb
      - PGDATA=/authdb-prod/data/postgres
    volumes:
      - authdb_data:/var/docker/taccaseapi
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend
#    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
#    profiles:
#      - production

  authsvr-prod:
    container_name: authsvr-prod
    image: pbranestrategy/tac-case-api-auth-server:0.1.3
    environment:
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb-prod:5432/tacauthdb
      - SPRING_DATASOURCE_USERNAME=tacauthuser
      - SPRING_DATASOURCE_PASSWORD=tacauthpass
      - AUTH_SVR_ENV=production
    tty: true
    stdin_open: true
    ports:
      - 9080:8080
    depends_on:
      authdb-prod:
        condition: service_healthy
    networks:
      - backend
#    restart: unless-stopped
#    profiles:
#      - production

  apisvc-prod:
    container_name: apisvc-prod
    image: pbranestrategy/tac-case-api-service:0.1.3
    environment:
      - SERVER_PORT=8080
      - AUTH_SVC_ISSUER_URI=http://authsvr-prod:8080/oauth2/jwks
      - API_SVR_ENV=production
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
#    restart: unless-stopped
#    profiles:
#      - production

  client-prod:
    container_name: client-prod
    image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.3
    environment:
      - AUTH_BASE_URI=http://authsvr-prod:8080
      - TOKEN_EP_URI=/oauth2/token
      - AUTH_EP_URI=/oauth2/authorize
      - USER_INFO_EP_URI=/oauth2/userinfo
      - JWK_SET_EP_URI=/oauth2/jwks
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - CLIENT_SCOPE=read.cases,write.cases
      - CLIENT_CONN_TIMEOUT=2000
      - CLIENT_RESP_TIMEOUT=3000
      - RESOURCE_BASE_URI=http://apisvc-prod:8080/api/v1
      - AUTH_BASE_URI=http://authsvr-prod:8080
    tty: true
    stdin_open: true
    networks:
      - backend
#    profiles:
#      - production

networks:
  backend:
    driver: bridge

volumes:
  authdb_data:

