apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f az-kompose-prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: apisvc-prod
  name: apisvc-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apisvc-prod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f az-kompose-prod.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: apisvc-prod
    spec:
      containers:
        - env:
            - name: API_SVR_ENV
              value: production
            - name: AUTH_SVC_ISSUER_URI
              value: http://authsvr-prod:8080/oauth2/jwks
            - name: SERVER_PORT
              value: "8080"
          image: pbranestrategy/tac-case-api-service:0.1.3
          name: apisvc-prod
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
