apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f az-kompose-prod2.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: apisvc-prod
  name: apisvc-prod
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: apisvc-prod
status:
  loadBalancer: {}
