apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f az-kompose-prod.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: authsvr-prod
  name: authsvr-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authsvr-prod
      io.kompose.service: authsvr-prod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f az-kompose-prod.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        app: authsvr-prod
        io.kompose.service: authsvr-prod
    spec:
      containers:
        - name: authsrv-prod
          image: pbranestrategy/tac-case-api-auth-server:0.1.3
          ports:
            - containerPort: 8080
          env:
          - name: AUTH_SVR_ENV
            value: production
          - name: CLIENT_ID
            value: client-id
          - name: CLIENT_NAME
            value: client-name
        - name: CLIENT_SECRET
          value: client-secret
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_PASSWORD
          value: tacauthpass
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://authdb-prod:5432/tacauthdb
        - name: SPRING_DATASOURCE_USERNAME
          value: tacauthuser
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
          resources: {}
      restartPolicy: Always
status: {}
