apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f az-kompose-prod2.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: client-prod
  name: client-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client-prod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f az-kompose-prod2.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: client-prod
    spec:
      containers:
        - env:
            - name: AUTH_BASE_URI
              value: http://authsvr-prod:8080
            - name: AUTH_EP_URI
              value: /oauth2/authorize
            - name: CLIENT_CONN_TIMEOUT
              value: "2000"
            - name: CLIENT_ID
              value: client-id
            - name: CLIENT_NAME
              value: client-name
            - name: CLIENT_RESP_TIMEOUT
              value: "3000"
            - name: CLIENT_SCOPE
              value: read.cases,write.cases
            - name: CLIENT_SECRET
              value: client-secret
            - name: JWK_SET_EP_URI
              value: /oauth2/jwks
            - name: RESOURCE_BASE_URI
              value: http://apisvc-prod:8080/api/v1
            - name: TOKEN_EP_URI
              value: /oauth2/token
            - name: USER_INFO_EP_URI
              value: /oauth2/userinfo
          image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.3
          name: client-prod
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
