FROM ubuntu:noble
RUN apt-get update && apt install -y bash bind9-utils dnsutils net-tools iputils-ping iputils-tracepath iproute2
#CMD ["bash"]
CMD ["/bin/bash", "-c", "while :; do sleep 2073600; done"]
